spring:
  application:
    name: gateway #注册到nacos的服务名
  cloud:
    nacos:
      server-addr: localhost:8848 #连接信息
      discovery:
        namespace: dev #注册到的具体命名空间
    gateway:
      globalcors:
        cors-configurations: #解决浏览器的跨域问题
          '[/**]': #拦截所有路径的请求
            allowed-origin-patterns: '*' #允许所有域名（来源）访问
            allowed-headers: '*' #允许所有请求头
            allowed-methods: '*' #允许所有 HTTP 方法（GET, POST, PUT, DELETE 等）
      routes: #路由规则定列表
        - id: student-service
          uri: lb://student-service    # lb 表示负载均衡，从 Nacos 获取实例
          predicates:
            - Path=/gateway/**         # 匹配路径
          filters:
            - RewritePath=/gateway/?(?<segment>.*),/$\{segment} #路径重写
            - AddResponseHeader=X-Gateway-Version, 1.0 #添加响应头，返回前端看的不能作为完全校验