# 自定义 JWT 配置
jwt:
  admin-secret-key: "thisisanexamplesecret_campus"
  admin-ttl: 43200000 #token有效时间
  admin-token-name: "student_login"
  redis-hours: 12 #redis存储时间
  admin-redis-hours: 2 #管理员redis存储时间
