# 自定义 JWT 配置
jwt:
  jwt-secret-key: "thisisanexamplesecret_campus"
  jwt-ttl: 43200000 #token有效时间
  jwt-token-name: "student_login"
  user-redis-hours: 12 #redis存储时间
  admin-redis-hours: 2 #管理员redis存储时间
