spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
          order-service:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
            retryable: true #开启重试机制

feign:
  sentinel:
    enabled: true
