profile:
  default-style:
    avatar: ""
    background: ""
    wallpaper: ""
    card-opacity: 1.00
    card-blur: 14.00
    global-font-enabled: 1
    wallpaper-mask: 1.00


  default-options:
    avatars:
      - /avatar/avatar_default_1.jpg
      - /avatar/avatar_default_2.jpg
    backgrounds:
      - /background/background_default_1.jpg
      - /background/background_default_2.jpg
    wallpapers:
      - /wallpaper/wallpaper_default_1.jpg
      - /wallpaper/wallpaper_default_2.jpg