spring:
  application:
    name: student-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery: #注册名称空间
        namespace: dev
        metadata: #元数据
          version: stable

      config: #获取配置名称空间
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yaml # 拼接配置文件 user-service-dev.yaml
  config:
    import:
      - nacos:datasource-mysql.yaml?group=DATASOURCE_GROUP
      - nacos:datasource-redis.yaml?group=DATASOURCE_GROUP
      - nacos:common-log.yaml?group=DEFAULT_GROUP
      - 