profile:
  default-style:
    avatar: http://localhost:8000/avatar/avatar_default_1.jpg
    background: http://localhost:8000/background/background_default_1.jpg
    wallpaper: http://localhost:8000/wallpaper/wallpaper_default_1.jpg
    card-opacity: 1.00
