server:
  port: 9000

internal:
  callback-token: ${JAVA_INTERNAL_TOKEN:}

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  profiles:
    include:
      - mybatis
      - jwt
      - nacos
      - sentinel
      - aes
