export const ADMIN_CONFIG = {
  LOGIN_SUFFIX: '/admin',
  LOGIN_MODE: {
    USER: 'user',
    ADMIN: 'admin'
  },
  TEXT: {
    PAGE_TITLE: 'Campus Assistant Admin',
    PAGE_SUBTITLE: 'Administration Console',
    SECTION_LABEL: 'Workspace',
    SECTION_RESOURCES: 'External Tools',
    SECTION_LOGS: 'Logs',
    RESOURCE_TITLE: 'Resources',
    RESOURCE_SUBTITLE: '管理员控制台入口',
    LOG_TITLE: 'Logs',
    LOG_SUBTITLE: '查看当天日志并下载历史压缩日志',
    EMPTY_TEXT: '当前未配置可跳转资源',
    LOG_EMPTY_TEXT: '当前没有可用日志文件',
    LOG_PLACEHOLDER: '请选择左侧日志文件',
    LOG_ACTIVE_HINT: '当前文件支持实时查看',
    LOG_HISTORY_HINT: '可向前加载更早日志',
    LOG_ARCHIVE_HINT: '历史压缩日志暂仅支持下载',
    LOG_RESET_HINT: '日志文件已切换，已自动重新定位到最新内容',
    LOG_REFRESHING: '实时轮询中...',
    LOG_POLLING_IDLE: '已停止轮询',
    LOG_START_POLLING: '开始轮询',
    LOG_STOP_POLLING: '停止轮询',
    LOG_POLLING_LABEL: '轮询日志',
    LOG_LOAD_HISTORY: '加载更早日志',
    LOG_NO_MORE_HISTORY: '没有更早日志了',
    LOG_LOADING_HISTORY: '正在加载更早日志...',
    LOG_REFRESH_ONCE: '单次刷新',
    LOG_RESET_CONSOLE: '重置控制台',
    LOG_SCROLL_TOP: '到顶部',
    LOG_SCROLL_BOTTOM: '到底部',
    LOG_DOWNLOAD: '下载日志',
    LOG_FILE_GROUP_ACTIVE: '当天文件',
    LOG_FILE_GROUP_ARCHIVE: '历史压缩',
    LOG_FILE_TYPE_ACTIVE: 'log',
    LOG_FILE_TYPE_ARCHIVE: 'gz',
    LOG_LAST_UPDATE: '最后更新',
    LOG_LIMIT_HINT: '已触发前端显示上限，可重置控制台恢复最新窗口',
    LOG_FILE_LIST_TITLE: '日志文件',
    LOADING_TEXT: '加载中...',
    LOGOUT_LABEL: '退出',
    RESOURCE_SEPARATOR: '：'
  },
  LAYOUT: {
    SIDEBAR_WIDTH: 248,
    SIDEBAR_PADDING_Y: 24,
    SIDEBAR_PADDING_X: 18,
    CONTENT_PADDING_TOP: 24,
    CONTENT_PADDING_X: 24,
    CONTENT_PADDING_BOTTOM: 32,
    PANEL_MAX_WIDTH: 920,
    TOOLBAR_MIN_HEIGHT: 64,
    TOOLBAR_PADDING_Y: 14,
    TOOLBAR_PADDING_X: 24,
    BUTTON_MIN_WIDTH: 72,
    BUTTON_HEIGHT: 34,
    BUTTON_PADDING_X: 14,
    ITEM_PADDING_Y: 18,
    PANEL_PADDING_Y: 8,
    PANEL_PADDING_X: 24,
    RESOURCE_NAME_SIZE: 16,
    RESOURCE_URL_SIZE: 14,
    MOBILE_BREAKPOINT: 960,
    MOBILE_RESOURCE_NAME_SIZE: 15,
    MOBILE_RESOURCE_URL_SIZE: 13,
    LOG_FILE_PANEL_WIDTH: 280,
    LOG_VIEWER_HEIGHT: 620,
    LOG_VIEWER_MIN_HEIGHT: 420,
    LOG_POLLING_INTERVAL: 2000,
    LOG_PREVIEW_LIMIT: 500,
    LOG_MAX_DISPLAY_LINES: 3000
  },
  THEME: {
    PAGE_BG: '#1e1f22',
    SIDEBAR_BG: '#2b2d30',
    MAIN_BG: '#1e1f22',
    TOOLBAR_BG: '#1f2023',
    PANEL_BG: '#25262a',
    SIDEBAR_ACTIVE_BG: '#365880',
    SIDEBAR_BORDER: '#3c3f41',
    PANEL_BORDER: '#31343a',
    BUTTON_BORDER: '#4a4f57',
    BUTTON_BORDER_HOVER: '#5c6168',
    BUTTON_BG: '#2b2d30',
    BUTTON_BG_HOVER: '#34373c',
    TEXT_PRIMARY: '#f3f4f6',
    TEXT_SECONDARY: '#9aa0a6',
    TEXT_MUTED: '#8b949e',
    TEXT_LINK: '#cdd6f4',
    TEXT_LINK_STRONG: '#dbe4ff',
    TEXT_LINK_MUTED: '#9aa3b2',
    TEXT_LINK_HOVER: '#7aa2ff',
    DIVIDER: 'rgba(255, 255, 255, 0.08)'
  }
}
