export const SCHEDULE_CONFIG = {
  TEXT: {
    PREV_WEEK_TITLE: '上一周',
    NEXT_WEEK_TITLE: '下一周',
    THIS_WEEK_BUTTON: '本周',
    FULL_TERM_BUTTON: '全学期',
    REFRESH_BUTTON: '刷新',
    CURRENT_WEEK_LABEL: '第 {week} 周',
    FULL_TERM_LABEL: '全学期课表',
    PERIOD_HEADER: '节',
    LOADING_TEXT: '加载课表中…',
    SYNCING_TITLE: '数据同步中',
    SYNCING_TEXT: '正在为您拉取最新课表，请稍候…',
    EMPTY_TERM_TEXT: '本学期暂无课程',
    EMPTY_WEEK_TEXT: '本周暂无课程',
    STACK_TITLE: '该时段有 {count} 门课',
    CLOSE_BUTTON: '关闭',
    FIELD_CLASSROOM: '教室',
    FIELD_TEACHER: '教师',
    FIELD_PERIOD: '节次',
    FIELD_WEEK: '周次',
    FIELD_CAMPUS: '校区',
    WEEKDAY_PREFIX: '周'
  },
  SEMESTER_START_DATE: '2025-02-17',
  MAX_WEEK: 25,
  TOTAL_PERIODS: 14,
  DESKTOP_ROW_HEIGHT: 58,
  MOBILE_ROW_HEIGHT: 52,
  MOBILE_BREAKPOINT: 768,
  SMALL_MOBILE_BREAKPOINT: 360,
  EMPTY_SCHEDULE_VALUES: ['', '[]', '{}'],
  DAYS: ['一', '二', '三', '四', '五', '六', '日'],
  PERIOD_TIME: [
    '08:00', '08:55', '09:50', '10:55', '11:50',
    '13:30', '14:25', '15:20', '16:25', '17:20',
    '18:30', '19:25', '20:20', '21:15'
  ],
  COURSE_COLORS: [
    ['#4f86f7', '#dbeafe'],
    ['#10b981', '#d1fae5'],
    ['#f97316', '#ffedd5'],
    ['#8b5cf6', '#ede9fe'],
    ['#ec4899', '#fce7f3'],
    ['#06b6d4', '#cffafe'],
    ['#f59e0b', '#fef3c7'],
    ['#ef4444', '#fee2e2'],
    ['#14b8a6', '#ccfbf1'],
    ['#6366f1', '#e0e7ff'],
    ['#84cc16', '#ecfccb'],
    ['#a855f7', '#f3e8ff']
  ],
  DEFAULT_COURSE_COLOR: '#4f86f7'
}
